### ISSUE TITLE
Docker Spring Boot

### ISSUE THREAD

**Issue by isaacmsl** [isaacmsl/bora-pagar#7]

**Comment by isaacmsl** [comment]
Desenvolvemos um _docker-compose.yml_ que faz sentido:
```
version: '5'

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'
    volumes:
     - type: bind
       source: ./backend
       target: /app
```

Junto com o seguinte _application.yml_:
```
spring:
  data:
    mongodb:
      uri: 'mongodb://mongodb:27017/bora-pagar'

server:
  port: 8080
```
