### ISSUE TITLE
Docker Vue.js

### ISSUE THREAD

**Issue by isaacmsl** [isaacmsl/bora-pagar#8]

**Comment by isaacmsl** [comment]
Tentei dockerizar de tal forma que os devs compartilhassem o mesmo ambiente de desenvolvimento, mas não consegui.

O `.dockerignore`:
```md
.dockerignore
Dockerfile
node_modules
.vscode
```

O `Dockerfile`:

```md

FROM node:lts-alpine

# instala um servidor http simples para servir conteúdo estático
RUN npm install -g http-server

# faz da pasta 'app' o diretório atual de trabalho
WORKDIR /app

# copia os arquivos 'package.json' e 'package-lock.json' (se disponível)
COPY package*.json ./

# instala dependências do projeto
RUN npm install

# copia arquivos e pastas para o diretório atual de trabalho (pasta 'app')
COPY . .

# compila a aplicação de produção com minificação
RUN npm run build

EXPOSE 8080
CMD [ "http-server", "dist" ]
```

O `docker-compose.yml`:
```
version: '3'

services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
```
